server:
  port: 8110
management:
  endpoints:
    web:
      exposure:
        include: "*"
feign:
  okhttp:
    enabled: true
ribbon:
  ConnectTimeout: 30000 #服务请求连接超时时间（毫秒）
  ReadTimeout: 30000 #服务请求处理超时时间（毫秒）
